CREATE TABLE IF NOT EXISTS products (

    id SERIAL PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    category VARCHAR(100),

    price DECIMAL(10,2) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);